ezplatform:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    toolbars:
                        paragraph:
                            buttons:
                                word_suggestion:
                                    priority: 900
ezrichtext:
    alloy_editor:
        extra_plugins: [word_suggestion]